=== ljm9748/miniminies/ERD/eXERD/configuration/org.eclipse.osgi/bundles/143/1/.cp/nl/ko/content/content.dtd
<?xml version="1.0" encoding="utf-8" ?>

<!ELEMENT introContent ((page | group)+ | (extensionContent | replacementContent))+ >
<!ELEMENT page (group | link | text | head | img | include | html | title | anchor | contentProvider)*>
<!ATTLIST page
id           CDATA #REQUIRED
url          CDATA #IMPLIED
style        CDATA #IMPLIED
alt-style    CDATA #IMPLIED
filteredFrom (swt|html) #IMPLIED
content      CDATA #IMPLIED
style-id     CDATA #IMPLIED
shared-style (true | false) "true"
bgImage      CDATA #IMPLIED>

<!ELEMENT group (group | link | text | img | include | html | anchor | contentProvider)*>
<!ATTLIST group
id           CDATA #REQUIRED
label        CDATA #IMPLIED
style-id     CDATA #IMPLIED
filteredFrom (swt|html) #IMPLIED
computed     (true | false) "false"
bgImage      CDATA #IMPLIED
expandable   (true | false) "false"
expanded     (true | false) "false">

<!ELEMENT head (#PCDATA)>
<!ATTLIST head
src      CDATA #REQUIRED
encoding CDATA #IMPLIED>
<!ELEMENT title (#PCDATA)>
<!ATTLIST title
id           CDATA #IMPLIED
style-id     CDATA #IMPLIED
filteredFrom (swt|html) #IMPLIED>

<!ELEMENT link (text? , img?)>
<!ATTLIST link
url          CDATA #REQUIRED
id           CDATA #IMPLIED
label        CDATA #IMPLIED
style-id     CDATA #IMPLIED
filteredFrom (swt|html) #IMPLIED>

<!ELEMENT text (#PCDATA)>
<!ATTLIST text
id           CDATA #IMPLIED
style-id     CDATA #IMPLIED
filteredFrom (swt|html) #IMPLIED>

<!ELEMENT img EMPTY>
<!ATTLIST img
src          CDATA #REQUIRED
id           CDATA #IMPLIED
alt          CDATA #IMPLIED
style-id     CDATA #IMPLIED
filteredFrom (swt|html) #IMPLIED >

<!ELEMENT html (img | text | EMPTY)>
<!ATTLIST html
id           CDATA #REQUIRED
src          CDATA #REQUIRED
type         (inline|embed) #IMPLIED
style-id     CDATA #IMPLIED
filteredFrom (swt|html) #IMPLIED
encoding     CDATA #IMPLIED>

<!ELEMENT include EMPTY>
<!ATTLIST include
path        CDATA #REQUIRED
configId    CDATA #IMPLIED
merge-style (true | false) "false" >

<!ELEMENT anchor EMPTY>
<!ATTLIST anchor
id CDATA #REQUIRED>

<!ELEMENT extensionContent (text | group | link | html | include)+>
<!ATTLIST extensionContent
path      CDATA #REQUIRED
style     CDATA #IMPLIED
alt-style CDATA #IMPLIED
content   CDATA #IMPLIED
id        CDATA #IMPLIED
name      CDATA #IMPLIED>

<!ELEMENT replacementContent (text | group | link | html | include)+>
<!ATTLIST replacementContent
path      CDATA #REQUIRED
style     CDATA #IMPLIED
alt-style CDATA #IMPLIED
content   CDATA #IMPLIED>

<!ELEMENT contentProvider (text?)>
<!ATTLIST contentProvider
id       CDATA #REQUIRED
class    CDATA #REQUIRED
pluginId CDATA #IMPLIED>

<!ELEMENT hr EMPTY>
<!ATTLIST hr
id           CDATA #IMPLIED
style-id     CDATA #IMPLIED
filteredFrom (swt|html) #IMPLIED>

=== ljm9748/miniminies/ERD/eXERD/configuration/org.eclipse.osgi/bundles/143/1/.cp/nl/ko/content/overview.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE introContent PUBLIC "introContent" "content.dtd">
<introContent>
	<!-- 오버뷰 페이지에 기여 -->
	<extensionContent id="exerd-overview" style="html/universal.css"
		name="Sample Extension" path="overview/@">
		<group style-id="content-group" id="exerd.intro.helpgroup">
			<link label="eXERD 환영 페이지" url="http://org.eclipse.ui.intro/showPage?id=exerdRoot"
				id="link-exerd-root" style-id="content-link">
				<text>eXERD의 환영 페이지로 이동합니다. 데모동영상 및 샘플을 볼 수 있습니다.</text>
			</link>
			<link label="eXERD 도움말"
				url="http://org.eclipse.ui.intro/showHelpTopic?id=/com.tomato.exerd.help/html/gettingstarted/newErdFile/newfile.html"
				id="link-exerd-help" style-id="content-link">
				<text>eXERD의 기본적인 사용방법을 익힙니다.</text>
			</link>
		</group>
	</extensionContent>

	<!-- 샘플 페이지에 기여 -->
	<extensionContent id="exerd-samples" style="html/universal.css"
		name="Sample Extension" path="samples/@">
		<group style-id="content-group" id="exerd.intro.helpgroup">
			<link label="eXERD 샘플 ERD 파일" url="http://org.eclipse.ui.intro/showPage?id=exerdExample"
				id="link-exerd-sample" style-id="content-link">
				<text>eXERD의 샘플 파일들을 둘러 봅니다.</text>
			</link>
		</group>
	</extensionContent>


	<!-- What's new 페이지에 기여 -->
	<extensionContent id="exerd-whatsnew" style="html/universal.css"
		path="whatsnew/@">
		<group style-id="content-group" id="exerd.intro.helpgroup">
			<link label="eXERD"
				url="http://org.eclipse.ui.intro/showHelpTopic?id=/com.tomato.exerd.help/html/releaseNotes/releaseNotes.html"
				style-id="content-link" id="link-exerd-news">
				<text>eXERD의 최근 또는 이전 업데이트 내역을 확인합니다.</text>
			</link>
		</group>
		<!-- http://org.eclipse.ui.intro/showHelpTopic?id=/org.eclipse.platform.doc.user/gettingStarted/intro/overview.htm -->
	</extensionContent>

</introContent>

=== ljm9748/miniminies/ERD/eXERD/configuration/org.eclipse.osgi/bundles/143/1/.cp/content/overview.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE introContent PUBLIC "introContent" "content.dtd">
<introContent>
	<!-- 오버뷰 페이지에 기여 -->
	<extensionContent id="exerd-overview" style="html/universal.css"
		name="Sample Extension" path="overview/@">
		<group style-id="content-group" id="exerd.intro.helpgroup">
			<link label="eXERD's welcome page" url="http://org.eclipse.ui.intro/showPage?id=exerdRoot"
				id="link-exerd-root" style-id="content-link">
				<text>eXERD's welcome page. You can see demo videos and sample.</text>
			</link>
			<link label="Help eXERD"
				url="http://org.eclipse.ui.intro/showHelpTopic?id=/com.tomato.exerd.help/html/gettingstarted/newErdFile/newfile.html"
				id="link-exerd-help" style-id="content-link">
				<text>Familiarize yourself with the basics of using eXERD.</text>
			</link>
		</group>
	</extensionContent>

	<!-- 샘플 페이지에 기여 -->
	<extensionContent id="exerd-samples" style="html/universal.css"
		name="Sample Extension" path="samples/@">
		<group style-id="content-group" id="exerd.intro.helpgroup">
			<link label="eXERD Sample ERD File" url="http://org.eclipse.ui.intro/showPage?id=exerdExample"
				id="link-exerd-sample" style-id="content-link">
				<text>eXERD view of the sample files.</text>
			</link>
		</group>
	</extensionContent>


	<!-- What's new 페이지에 기여 -->
	<extensionContent id="exerd-whatsnew" style="html/universal.css"
		path="whatsnew/@">
		<group style-id="content-group" id="exerd.intro.helpgroup">
			<link label="eXERD"
				url="http://org.eclipse.ui.intro/showHelpTopic?id=/com.tomato.exerd.help/html/releaseNotes/releaseNotes.html"
				style-id="content-link" id="link-exerd-news">
				<text>Check eXERD recent or previous update history.</text>
			</link>
		</group>
		<!-- http://org.eclipse.ui.intro/showHelpTopic?id=/org.eclipse.platform.doc.user/gettingStarted/intro/overview.htm -->
	</extensionContent>

</introContent>
